Repository voxpupuli/ra10ke, pull requests merged in 2022-05, with the labels that each got.

#75 Fix #74 - server responded with 400
  lib/ra10ke/puppetfile_parser.rb
  spec/fixtures/Puppetfile_deprecation_issue
  spec/ra10ke/deprecation_spec.rb
Labels: bug

#77 Bump minimal Ruby Version 2.4.0->2.7.0
  .github/workflows/test.yml
  ra10ke.gemspec
Labels: backwards-incompatible

#79 CI: Do not run twice
  .github/workflows/test.yml
Labels: bug

#78 Add Ruby 3.1 support
  .github/workflows/test.yml
Labels: enhancement

#76 Converts puppet forge module entries into puppetfile git entries
  README.md
  lib/ra10ke.rb
  lib/ra10ke/dependencies.rb
  lib/ra10ke/git_repo.rb
  spec/fixtures/Puppetfile_git_conversion
  spec/ra10ke/dependencies_spec.rb
  spec/ra10ke/git_repo_spec.rb
Labels: enhancement

#80 Release 2.0.0
  CHANGELOG.md
  lib/ra10ke/version.rb
Labels: skip-changelog
