Repository voxpupuli/ra10ke, pull requests merged in 2023-08, with the labels that each got.

#85 Drop Ruby 2.6 support & Implement voxpupuli-rubocop
  .rubocop.yml
  .rubocop_todo.yml
  .ruby-version
  Gemfile
  Rakefile
  lib/ra10ke.rb
  lib/ra10ke/dependencies.rb
  lib/ra10ke/duplicates.rb
  lib/ra10ke/git_repo.rb
  lib/ra10ke/install.rb
  lib/ra10ke/monkey_patches.rb
  lib/ra10ke/puppetfile_parser.rb
  lib/ra10ke/solve.rb
  lib/ra10ke/syntax.rb
  lib/ra10ke/validate.rb
  lib/ra10ke/version.rb
  ra10ke.gemspec
  spec/ra10ke/dependencies_spec.rb
  spec/ra10ke/deprecation_spec.rb
  spec/ra10ke/git_repo_spec.rb
  spec/ra10ke/puppetfile_parser_spec.rb
  spec/ra10ke/validate_spec.rb
  spec/ra10ke_spec.rb
  spec/spec_helper.rb
Labels: backwards-incompatible

#86 Add exit codes to dependency check
  lib/ra10ke/dependencies.rb
Labels: backwards-incompatible

#89 Add Ruby 3.2 support / apply Vox Pupuli CI best practices
  .github/workflows/test.yml
Labels: enhancement

#92 Release 3.0.0
  CHANGELOG.md
  lib/ra10ke/version.rb
Labels: skip-changelog
